# Generated by Django 4.2 on 2023-05-22 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0002_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maxsulotlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=30)),
                ('narxi', models.IntegerField(max_length=30, unique=True)),
                ('rasm', models.CharField(max_length=300)),
                ('malumot', models.CharField(blank=True, max_length=30, null=True)),
                ('turi', models.CharField(max_length=30)),
            ],
        ),
    ]
