# Generated by Django 4.2 on 2023-05-23 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0003_maxsulotlar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maxsulotlar',
            name='narxi',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='tg_id',
            field=models.IntegerField(unique=True),
        ),
    ]
