# Generated by Django 4.2 on 2023-05-24 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0004_alter_maxsulotlar_narxi_alter_subscribe_tg_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Korzinka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=30)),
                ('narxi', models.IntegerField(unique=True)),
                ('rasm', models.CharField(max_length=300)),
                ('malumot', models.CharField(blank=True, max_length=30, null=True)),
                ('turi', models.CharField(max_length=30)),
                ('soni', models.IntegerField()),
                ('tg_id', models.IntegerField()),
                ('username', models.CharField(max_length=30)),
                ('date', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
