# Generated by Django 4.2 on 2023-05-24 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0006_alter_korzinka_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='korzinka',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='korzinka',
            name='narxi',
            field=models.IntegerField(),
        ),
    ]
