from . import menu_uchun
from . import ichimliklar_uchun
from . import taomlar_uchun
from . import taomlar1_uchun
from . import taomlar2_uchun
from . import salqin_ichimliklar_uchun
#from . import alkagollar_uchun
from . import orqaga
from . import menu_en
from . import foods1
from . import foods
from . import foods2
from . import drinks
from . import cool_ichimliklar
#from . import alcahol